core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from studentApp.views import *

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('loginApp.urls')),
    path('', include('studentApp.urls')),
    path('', include('forumApp.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginApp/urls.py
from os import name
from django.urls import path

from . import views

app_name = 'loginApp'

urlpatterns = [
    path('', views.login_page),
    path('login/', views.login_page, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_user, name='logout'),
]

loginApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING, related_name='student_user')
    fullname = models.CharField(max_length=200, default='UNKNOWN')
    department = models.CharField(max_length=10, default='UNKNOWN')
    semester = models.CharField(max_length=50)
    student_id = models.CharField(max_length=10, primary_key=True)
    address = models.CharField(max_length=500, default='UNKNOWN')
    cgpa = models.DecimalField(max_digits=3, decimal_places=2, blank=True, null=True)
    credit_taken = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True) 
    credit_completed = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='student_profile', blank=True, null=True)

    def __str__(self):
        return self.student_id

loginApp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from .models import Student

# Create your views here.
def register(request):

    registered = False

    if request.method == 'POST':
        fullname = request.POST['fullname']
        username = request.POST['username']
        department = request.POST['department']
        semester = request.POST['semester']
        student_id = request.POST['student_id']
        address = request.POST['address']
        email = request.POST['email']
        password = request.POST['password']
        
        user_obj = User(username=username, email=email)
        user_obj.set_password(password)
        user_obj.save()

        student_obj = Student(
            user = user_obj,
            fullname = fullname,
            department = department,
            semester = semester,
            student_id = student_id,
            address = address,
        )
        student_obj.save()

        return HttpResponseRedirect(reverse('loginApp:login'))

    else:    
        context = {}
        template_name = 'loginApp/register.html'
        return render(request, template_name, context)

def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('studentApp:profile'))
             
        else:
            return HttpResponse("invalid login information!")

    else:
        context = {}
        template_name = 'loginApp/login.html'
        return render(request, template_name, context)


@login_required 
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('loginApp:login'))

templates/loginApp/login.html
{% load static %}

<!DOCTYPE html>
<head>
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login_register2.css' %}">
    <link rel="stylesheet" href="{% static 'css/login_register1.css' %}">
</head>

<body>

    <div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" name="loginForm" action="#" method="POST" onsubmit="return validateForm()">
					{% csrf_token %}
					<span class="login100-form-title p-b-34">
						Account Login
					</span>
					
					<div class="wrap-input100 rs1-wrap-input100 validate-input m-b-20" data-validate="Type user name">
						<input id="first-name" class="input100" type="text" name="username" placeholder="User name">
						<span class="focus-input100"></span>
					</div>
					<div class="wrap-input100 rs2-wrap-input100 validate-input m-b-20" data-validate="Type password">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
					</div>
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn" value="Login">
							Sign in
						</button>
					</div>

					<div class="w-full text-center p-t-27 p-b-239">
						<span class="txt1">
						</span>

						<a href="{% url 'loginApp:register' %}" class="txt2">
							Sign Up
						</a>
					</div>

					
				</form>

				<div class="login100-more" >

					<style>
						.login100-more{
							background-image: url("{% static 'images/background.jpg' %}");
						}
					</style>
					
				</div>
			</div>
		</div>
	</div>
	
	

	<div id="dropDownSelect1"></div>
    
</body>

</html>

templates/loginApp/register.html
{% load static %}
<!DOCTYPE html>
<head>
    <title>SignUp</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login_register2.css' %}">
    <link rel="stylesheet" href="{% static 'css/login_register1.css' %}">
</head>

<body>

    <div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form name="registerForm" action="#" method="POST" class="login100-form validate-form">
					{% csrf_token %}
					<span class="login100-form-title p-b-34">
						Register
					</span>
					
					<div class="wrap-input100 rs1-wrap-input100 validate-input m-b-20" data-validate="Type user name">
						<input id="first-name" class="input100" type="text" name="fullname" placeholder="Full Name">
						<span class="focus-input100"></span>
					</div>
					<div class="wrap-input100 rs2-wrap-input100 validate-input m-b-20" data-validate="Type password">
						<input class="input100" type="text" name="username" placeholder="User Name">
						<span class="focus-input100"></span>
					</div>

                    <div class="wrap-input100 rs1-wrap-input100 validate-input m-b-20" data-validate="Type user name">
						<input id="first-name" class="input100" type="text" name="department" placeholder="Department">
						<span class="focus-input100"></span>
					</div>
					<div class="wrap-input100 rs2-wrap-input100 validate-input m-b-20" data-validate="Type password">
						<input class="input100" type="text" name="semester" placeholder="Semester">
						<span class="focus-input100"></span>
					</div>

                    <div class="wrap-input100 rs1-wrap-input100 validate-input m-b-20" data-validate="Type user name">
						<input id="first-name" class="input100" type="text" name="student_id" placeholder="Student ID">
						<span class="focus-input100"></span>
					</div>
					<div class="wrap-input100 rs1-wrap-input100 validate-input m-b-20" data-validate="Type user name">
						<input id="first-name" class="input100" type="text" name="address" placeholder="Address">
						<span class="focus-input100"></span>
					</div>

                    <div class="wrap-input100 rs1-wrap-input100 validate-input m-b-20" data-validate="Type user name">
						<input id="first-name" class="input100" type="text" name="email" placeholder="Email">
						<span class="focus-input100"></span>
					</div>
					<div class="wrap-input100 rs2-wrap-input100 validate-input m-b-20" data-validate="Type password">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
					</div>
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Sign Up
						</button>
					</div>

					<div class="w-full text-center p-t-27 p-b-239">
						<span class="txt1">
							Already have an account?
						</span>

						<a href="{% url 'loginApp:login' %}" class="txt2">
							Click here
						</a>
					</div>
				</form>

				<div class="login100-more" >

					<style>
						.login100-more{
							background-image: url("{% static 'images/sign_up_background.jpg' %}");
						}
					</style>
					
				</div>
			</div>
		</div>
	</div>
	
	

	<div id="dropDownSelect1"></div>
    
</body>

</html>