core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from studentApp.views import *

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('loginApp.urls')),
    path('', include('studentApp.urls')),
    path('', include('forumApp.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forumApp/urls.py
from django.urls import path

from . import views

app_name = 'forumApp'

urlpatterns = [
    path('forum/', views.forum, name='forum'),
    path('question/<str:pk>/', views.discussion_view, name='discussion'),
]

loginApp/urls.py
from os import name
from django.urls import path

from . import views

app_name = 'loginApp'

urlpatterns = [
    path('', views.login_page),
    path('login/', views.login_page, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_user, name='logout'),
]

studentApp/urls.py
from os import name
from django.urls import path

from . import views

app_name = 'studentApp'

urlpatterns = [
    path('developers/', views.dev_page, name='dev-page'), # uploaded
    path('profile/', views.profile_view, name = 'profile'), #done
    path('routine/', views.routine_view, name = 'routine'), #done
    path('schedule_checker/', views.schedule_checker_view, name = 'schedule_checker'),
    path('progress/', views.progress_view, name = 'progress'),
    path('instructor/', views.instructor_view, name = 'instructor'), #done
    path('finances/', views.finances_view, name = 'finances'),
    path('bus_schedule/', views.bus_schedule_view, name = 'bus_schedule'), #uploaded
    path('more_about_courses/', views.more_about_courses_view, name = 'more_about_courses'),
    path('course_catalog/', views.course_catalog_view, name = 'course_catalog'), 
]

templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title_block %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    {% block css_content %} {% endblock %}
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
    {% block js_content %} {% endblock %}
</head>
<body>
    {% include 'sidebar.html' %}

    {% block body_content %}

    {% endblock %}
</body>
</html>

templates/bus_schedule.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
  <title>Bus Schedule</title>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>

<input type="checkbox" id="check">
    <!--header area start-->
    <header>
      <label for="check">
        <div class="left_area">
          <h3 style="color:#fff">EDUQuest</h3>
        <i class="fas fa-bars" id="sidebar_btn"></i></div>
      </label>
         
            <div class="right_area">
              <a href="{% url 'loginApp:logout' %}" class="logout_btn">Logout</a>
              <a href="{% url 'studentApp:profile' %}" class="logout_btn">Home</a>
    
            </div>


        </header>
        <!--header area end-->
        <!--mobile navigation bar start-->
        <div class="mobile_nav">
          <div class="nav_bar">
            <img src="{% static 'images/logo.png' %}" class="mobile_profile_image" alt="">
            <i class="fa fa-bars nav_btn"></i>
          </div>
          <div class="mobile_nav_items">
            <a href="{% url 'studentApp:more_about_courses' %}"><i class="fas fa-book"></i><span>More about Courses</span></a>
      <a href="{% url 'studentApp:routine' %}"><i class="far fa-clock"></i><span>Personalized Routine</span></a>
      <a href="{% url 'studentApp:schedule_checker' %}"><i class="far fa-calendar-check"></i><span>Schedule Checker</span></a>
      <a href="{% url 'studentApp:progress' %}"><i class="fas fa-tasks"></i><span>Course Progress</span></a>
      <a href="{% url 'studentApp:instructor' %}"><i class="fas fa-chalkboard-teacher"></i><span>Instructor Profile</span></a>
      <a href="{% url 'studentApp:finances' %}"><i class="fas fa-donate"></i><span>Finances</span></a>
      <a href="{% url 'forumApp:forum' %}"><i class="fas fa-comments"></i><span>Discussion Forum</span></a>
      <a href="{% url 'studentApp:bus_schedule' %}"><i class="fas fa-bus"></i><span>Bus Schedule</span></a>
          </div>
        </div>
        <!--mobile navigation bar end-->
        <!--sidebar start-->
        <div class="sidebar">
          <div class="profile_info">
            <img src="{% static 'images/logo.png' %}" class="profile_image" alt="">
           
          </div>
      <a href="{% url 'studentApp:more_about_courses' %}"><i class="fas fa-book"></i><span>More about Courses</span></a>
      <a href="{% url 'studentApp:routine' %}"><i class="far fa-clock"></i><span>Personalized Routine</span></a>
      <a href="{% url 'studentApp:schedule_checker' %}"><i class="far fa-calendar-check"></i><span>Schedule Checker</span></a>
      <a href="{% url 'studentApp:progress' %}"><i class="fas fa-tasks"></i><span>Course Progress</span></a>
      <a href="{% url 'studentApp:instructor' %}"><i class="fas fa-chalkboard-teacher"></i><span>Instructor Profile</span></a>
      <a href="{% url 'studentApp:finances' %}"><i class="fas fa-donate"></i><span>Finances</span></a>
      <a href="{% url 'forumApp:forum' %}"><i class="fas fa-comments"></i><span>Discussion Forum</span></a>
      <a href="{% url 'studentApp:bus_schedule' %}"><i class="fas fa-bus"></i><span>Bus Schedule</span></a>
        </div>
    
    <div class="content">
      
    
        <meta name="author" content="Codeconvey" />
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900&display=swap" rel="stylesheet"><link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css'>
    
        <!--Only for demo purpose - no need to add.-->
        <link rel="stylesheet" href="{% static 'css/student_profile1.css' %}"/>
        
            <link rel="stylesheet" href="{% static 'css/student_profile2.css' %}">




</head>
<body>

<h2>EDU Bus Schedule</h2>

<table>
  <tr>
    <th>Time</th>
    <th>Route</th>
    <th>Bus No.</th>
  </tr>
  {% for r in route %}
  <tr>
    {% with time=r.timeslot_id|cut:"Mon" %}
    <td>{{ time|cut:"None"}}</td>
    {% endwith %}
    <td>{{r.route_name}}</td>
    <td>{{r.shuttle_id}}</td>
  </tr>
  {% endfor %}
</table>
 <br><br><br>
<section class="footer">
  <center>
  <div class="footer-desc">
  &copy;EDUQuest 2021. Developed with <span style="color: red; font-size: 1.5rem">❤</span> by EDUQuest.
  </div>
</center>
</section>  

  <style>
    .footer{
      background: #121212;
      color: #fff;
      
    }

    .footer .footer-desc{
      margin-top: 40px;
    }
  </style>
</body>
</html>


templates/instructor.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instructor Profile</title>
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" charset="utf-8"></script>
  </head>
  <body>
      
    <input type="checkbox" id="check">
    <!--header area start-->
    <header>
      <label for="check">
        <div class="left_area">
          <h3 style="color:#fff">EDUQuest</h3>
        <i class="fas fa-bars" id="sidebar_btn"></i></div>
      </label>
         
            <div class="right_area">
              <a href="{% url 'loginApp:logout' %}" class="logout_btn">Logout</a>
              <a href="{% url 'studentApp:profile' %}" class="logout_btn">Home</a>
    
            </div>


        </header>
        <!--header area end-->
        <!--mobile navigation bar start-->
        <div class="mobile_nav">
          <div class="nav_bar">
            <img src="{% static 'images/logo.png' %}" class="mobile_profile_image" alt="">
            <i class="fa fa-bars nav_btn"></i>
          </div>
          <div class="mobile_nav_items">
            <a href="{% url 'studentApp:more_about_courses' %}"><i class="fas fa-book"></i><span>More about Courses</span></a>
      <a href="{% url 'studentApp:routine' %}"><i class="far fa-clock"></i><span>Personalized Routine</span></a>
      <a href="{% url 'studentApp:schedule_checker' %}"><i class="far fa-calendar-check"></i><span>Schedule Checker</span></a>
      <a href="{% url 'studentApp:progress' %}"><i class="fas fa-tasks"></i><span>Course Progress</span></a>
      <a href="{% url 'studentApp:instructor' %}"><i class="fas fa-chalkboard-teacher"></i><span>Instructor Profile</span></a>
      <a href="{% url 'studentApp:finances' %}"><i class="fas fa-donate"></i><span>Finances</span></a>
      <a href="{% url 'forumApp:forum' %}"><i class="fas fa-comments"></i><span>Discussion Forum</span></a>
      <a href="{% url 'studentApp:bus_schedule' %}"><i class="fas fa-bus"></i><span>Bus Schedule</span></a>
          </div>
        </div>
        <!--mobile navigation bar end-->
        <!--sidebar start-->
        <div class="sidebar">
          <div class="profile_info">
            <img src="{% static 'images/logo.png' %}" class="profile_image" alt="">
           
          </div>
          <a href="{% url 'studentApp:more_about_courses' %}"><i class="fas fa-book"></i><span>More about Courses</span></a>
      <a href="{% url 'studentApp:routine' %}"><i class="far fa-clock"></i><span>Personalized Routine</span></a>
      <a href="{% url 'studentApp:schedule_checker' %}"><i class="far fa-calendar-check"></i><span>Schedule Checker</span></a>
      <a href="{% url 'studentApp:progress' %}"><i class="fas fa-tasks"></i><span>Course Progress</span></a>
      <a href="{% url 'studentApp:instructor' %}"><i class="fas fa-chalkboard-teacher"></i><span>Instructor Profile</span></a>
      <a href="{% url 'studentApp:finances' %}"><i class="fas fa-donate"></i><span>Finances</span></a>
      <a href="{% url 'forumApp:forum' %}"><i class="fas fa-comments"></i><span>Discussion Forum</span></a>
      <a href="{% url 'studentApp:bus_schedule' %}"><i class="fas fa-bus"></i><span>Bus Schedule</span></a>
        </div>
        
    
    <div class="content">
      
    
        <meta name="author" content="Codeconvey" />
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900&display=swap" rel="stylesheet"><link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css'>
    
        <!--Only for demo purpose - no need to add.-->
        <link rel="stylesheet" href="{% static 'css/inst_profile1.css' %}" />
        
            <link rel="stylesheet" href="{% static 'css/inst_profile2.css' %}">
    </head>
    <body>
      
      <form action="/action_page.php">
        <h2><label for="cars">Choose an instructor:</label></h2> 
        <br>
         <select name="courses" id="courses" style="width: 300px;">  
          {% for instructor in instructors %}
           <option >{{instructor.name}} ({{instructor.dept_name}})</option>
          {% endfor %} 
         </select>
         <button><a href = "#">Go</a></button>
       </form>
            
 
    
  
    
    <section>
        <div class="rt-container">
              <div class="col-rt-12">
                  <div class="Scriptcontent">
                  
    <!-- Student Profile -->
    <div class="student-profile py-4">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <div class="card shadow-sm">
              <div class="card-header bg-transparent text-center">
                <img class="profile_img" src="{% static 'images/nazim.png' %}"alt="instructor dp">
                <h3>Dr. Mohammed Nazim Uddin</h3>
              </div>
              <div class="card-body">
                
                <h6>Professor & Associate Dean</h6>
                <h6 >School of Science & Engineering</h6>
                <h6>Email: nazim@eastdelta.edu.bd</h6>
              </p>
                
              
                
              </div>
            </div>
          </div>
          <div class="col-lg-8">
            <div class="card shadow-sm">
              <div class="card-header bg-transparent border-0">
                <h3 class="mb-0"><i class="far fa-clone pr-1"></i>Educational Qualification:</h3>
              </div>
              <div class="card-body pt-0">
                <table class="table table-bordered">
                 
                  
                  <tr>
                    <td width="30%">Doctor of Philosophy (PhD) Computer Science and Engineering<br>Inha University</td>
                    <td width ="4%">South Korea</td>
                  </tr>
                    <td width ="30%">Master of Computer Science<br>University of Pune</td>
                    <td width ="2%">India</td>
                  </tr>
                  <tr>
                    <td >Bachelor of Computer Science<br>University of Pune</td>
                     <td width ="2%">India</td>
                  </tr>
                  
                  
                </table>
                <h3 class="mb-0"><i class="far fa-clone pr-1"></i>Researches & Publications </h3>
                <table class="table table-bordered">
                 
                  <tr><td>
                    1. <a href="https://scholar.google.com/citations?view_op=view_citation&hl=en&user=EtpxnzQAAAAJ&citation_for_view=EtpxnzQAAAAJ:LkGwnXOMwfcC">Semantic similarity measures for enhancing information retrieval in folksonomies
MN Uddin, TH Duong, NT Nguyen, XM Qi, GS Jo
Expert Systems with Applications 40 (5), 1645-1653</a>
</td></tr>
                  <tr>
                    <td>
                      2. <a href ="https://scholar.google.com/citations?view_op=view_citation&hl=en&user=EtpxnzQAAAAJ&citation_for_view=EtpxnzQAAAAJ:Y0pCki6q_DkC">The IoT: Exciting possibilities for bettering lives: Special application scenarios
SMR Islam, MN Uddin, KS Kwak
IEEE Consumer Electronics Magazine 5 (2), 49-57</a>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      3.<a href= "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=EtpxnzQAAAAJ&citation_for_view=EtpxnzQAAAAJ:ufrVoPGSRksC">  Contextual information search based on ontological user profile
NU Mohammed, TH Duong, GS Jo
International Conference on Computational Collective Intelligence, 490-500</a><br>
<a href ="https://scholar.google.com/citations?user=EtpxnzQAAAAJ&hl=en">see more</a>
                    </td>
                  </tr>
                  
                </table>
              </div>
            </div>
              <div style="height: 26px"></div>
            
          </div>
        </div>
      </div>
    </div>
    <!-- partial -->
               
                </div>
            </div>
        </div>
    </section>
         
    
   <section class="footer">
      <center>
      <div class="footer-desc">
      &copy;EDUQuest 2021. Developed with <span style="color: red; font-size: 1.5rem">❤</span> by EDUQuest.
      </div>
    </center>
  </section>  
  
      <style>
        .footer{
          background: #121212;
          color: #fff;
          
        }

        .footer .footer-desc{
          margin-top: 40px;
        }
      </style> 
      
  </body>
</html>

templates/more_about_courses.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

  <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
  <title>More about Courses</title> 
<style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #600024;
  color: white;
}

#courses{
  font-size: large;
}

.submit-button{
    position: absolute;
  left: 1500px;
  
  
  }

  .btn{
    padding: 10px,20px;
  }
</style>

<input type="checkbox" id="check">
    <!--header area start-->
    <header>
      <label for="check">
        <div class="left_area">
          <h3 style="color:#fff">EDUQuest</h3>
        <i class="fas fa-bars" id="sidebar_btn"></i></div>
      </label>
         
            <div class="right_area">
              <a href="{% url 'loginApp:logout' %}" class="logout_btn">Logout</a>
              <a href="{% url 'studentApp:profile' %}" class="logout_btn">Home</a>
    
            </div>
</header>
<!--header area end-->
<!--mobile navigation bar start-->
<div class="mobile_nav">
  <div class="nav_bar">
    <img src="{% static 'images/logo.png' %}" class="mobile_profile_image" alt="">
    <i class="fa fa-bars nav_btn"></i>
  </div>
  <div class="mobile_nav_items">
    <a href="{% url 'studentApp:more_about_courses' %}"><i class="fas fa-book"></i><span>More about Courses</span></a>
  <a href="{% url 'studentApp:routine' %}"><i class="far fa-clock"></i><span>Personalized Routine</span></a>
  <a href="{% url 'studentApp:schedule_checker' %}"><i class="far fa-calendar-check"></i><span>Schedule Checker</span></a>
  <a href="{% url 'studentApp:progress' %}"><i class="fas fa-tasks"></i><span>Course Progress</span></a>
  <a href="{% url 'studentApp:instructor' %}"><i class="fas fa-chalkboard-teacher"></i><span>Instructor Profile</span></a>
  <a href="{% url 'studentApp:finances' %}"><i class="fas fa-donate"></i><span>Finances</span></a>
  <a href="{% url 'forumApp:forum' %}"><i class="fas fa-comments"></i><span>Discussion Forum</span></a>
  <a href="{% url 'studentApp:bus_schedule' %}"><i class="fas fa-bus"></i><span>Bus Schedule</span></a>
  </div>
</div>
<!--mobile navigation bar end-->
<!--sidebar start-->
<div class="sidebar">
  <div class="profile_info">
    <img src="{% static 'images/logo.png' %}" class="profile_image" alt="">
   
  </div>
  <a href="{% url 'studentApp:more_about_courses' %}"><i class="fas fa-book"></i><span>More about Courses</span></a>
  <a href="{% url 'studentApp:routine' %}"><i class="far fa-clock"></i><span>Personalized Routine</span></a>
  <a href="{% url 'studentApp:schedule_checker' %}"><i class="far fa-calendar-check"></i><span>Schedule Checker</span></a>
  <a href="{% url 'studentApp:progress' %}"><i class="fas fa-tasks"></i><span>Course Progress</span></a>
  <a href="{% url 'studentApp:instructor' %}"><i class="fas fa-chalkboard-teacher"></i><span>Instructor Profile</span></a>
  <a href="{% url 'studentApp:finances' %}"><i class="fas fa-donate"></i><span>Finances</span></a>
  <a href="{% url 'forumApp:forum' %}"><i class="fas fa-comments"></i><span>Discussion Forum</span></a>
  <a href="{% url 'studentApp:bus_schedule' %}"><i class="fas fa-bus"></i><span>Bus Schedule</span></a>
</div>

<div class="content">
  

    <meta name="author" content="Codeconvey" />
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900&display=swap" rel="stylesheet"><link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css'>

    <!--Only for demo purpose - no need to add.-->
    <link rel="stylesheet" href="{% static 'css/studentApp/demo.css' %}" />
    
        <link rel="stylesheet" href="{% static 'css/studentApp/studentProfile.css' %}">



</head>
<body>

 

<h1>Course Tables</h1>
<br>
<table id="customers">
  <tr>
    <th>Completed Courses</th>
    
  </tr>
  {% for completed_course in completed %}
  <tr>
    <td>{{completed_course.course_id}}</td>
    {% endfor %}
  </tr>

</table>
<br> 

<table id="customers">
  <tr>
    <th>Not Completed Courses</th>
    
  </tr>
  {% for not_completed_course in notcompleted %}
  <tr>
    <td>{{not_completed_course.course_id}}</td>
    {% endfor %}
  </tr>

</table>

<section class="footer">
      <center>
      <div class="footer-desc">
      &copy;EDUQuest 2021. Developed with <span style="color: red; font-size: 1.5rem">❤</span> by EDUQuest.
      </div>
    </center>
  </section>  
  
      <style>
        .footer{
          background: #121212;
          color: #fff;
          
        }

        .footer .footer-desc{
          margin-top: 40px;
        }
      </style>

</body>
</html>



templates/schedule_checker.html
{% load static %}


  <!DOCTYPE html>
  <html lang="en" dir="ltr">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Student Profile</title>
      <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
      
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" charset="utf-8"></script>
    
  
  <style>
  .f5{
     display: flex
  }
.square {
  height: 20px;
  width: 20px;
  background-color: green;
 
}
</style>
<style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #600024;
  color: white;
}

#courses{
  font-size: large;
}

.submit-button{
    position: absolute;
  left: 1500px;
  
  
  }

  .btn{
    padding: 10px,20px;
  }
</style>


    

</head>

<input type="checkbox" id="check">
<!--header area start-->
<header>
  <label for="check">
    <div class="left_area">
      <h3 style="color:#fff">EDUQuest</h3>
    <i class="fas fa-bars" id="sidebar_btn"></i></div>
  </label>
     
        <div class="right_area">
          <a href="{% url 'loginApp:logout' %}" class="logout_btn">Logout</a>

        </div>

    </header>
    <!--header area end-->
    <!--mobile navigation bar start-->
    <div class="mobile_nav">
      <div class="nav_bar">
        <img src="{% static 'images/logo.png' %}" class="mobile_profile_image" alt="">
        <i class="fa fa-bars nav_btn"></i>
      </div>
      <div class="mobile_nav_items">
  <a href="{% url 'studentApp:more_about_courses' %}"><i class="fas fa-book"></i><span>More about Courses</span></a>
  <a href="{% url 'studentApp:routine' %}"><i class="far fa-clock"></i><span>Personalized Routine</span></a>
  <a href="{% url 'studentApp:schedule_checker' %}"><i class="far fa-calendar-check"></i><span>Schedule Checker</span></a>
  <a href="{% url 'studentApp:progress' %}"><i class="fas fa-tasks"></i><span>Course Progress</span></a>
  <a href="{% url 'studentApp:instructor' %}"><i class="fas fa-chalkboard-teacher"></i><span>Instructor Profile</span></a>
  <a href="{% url 'studentApp:finances' %}"><i class="fas fa-donate"></i><span>Finances</span></a>
  <a href="{% url 'forumApp:forum' %}"><i class="fas fa-comments"></i><span>Discussion Forum</span></a>
  <a href="{% url 'studentApp:bus_schedule' %}"><i class="fas fa-bus"></i><span>Bus Schedule</span></a>
      </div>
    </div>
    <!--mobile navigation bar end-->
    <!--sidebar start-->
    <div class="sidebar">
      <div class="profile_info">
        <img src="{% static 'images/logo.png' %}" class="profile_image" alt="">
       
      </div>
      <a href="{% url 'studentApp:more_about_courses' %}"><i class="fas fa-book"></i><span>More about Courses</span></a>
  <a href="{% url 'studentApp:routine' %}"><i class="far fa-clock"></i><span>Personalized Routine</span></a>
  <a href="{% url 'studentApp:schedule_checker' %}"><i class="far fa-calendar-check"></i><span>Schedule Checker</span></a>
  <a href="{% url 'studentApp:progress' %}"><i class="fas fa-tasks"></i><span>Course Progress</span></a>
  <a href="{% url 'studentApp:instructor' %}"><i class="fas fa-chalkboard-teacher"></i><span>Instructor Profile</span></a>
  <a href="{% url 'studentApp:finances' %}"><i class="fas fa-donate"></i><span>Finances</span></a>
  <a href="{% url 'forumApp:forum' %}"><i class="fas fa-comments"></i><span>Discussion Forum</span></a>
  <a href="{% url 'studentApp:bus_schedule' %}"><i class="fas fa-bus"></i><span>Bus Schedule</span></a>
    </div>
   
    <div class="content">
      
    
      <meta name="author" content="Codeconvey" />
      <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900&display=swap" rel="stylesheet"><link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css'>
  

     
      
         
   

<body>
  <h1><b>Schedule Checker</b></h1> <br>

  <form action="/action_page.php">
   <h2><label for="cars">Select course you want to add : <address></address></label></h2> 
    <select name="courses" id="courses" style="width: 150px;">
      <option value="CSE300">CSE300</option>
      <option value="CSE443">CSE443</option>
    </select>
  </form>
  <form action="/action_page.php">
   <h2><label for="cars">Select Time slot for course :</label></h2> 
    <select name="courses" id="courses" style="width: 150px;">
      <option value="10.00am-11.30am">10.00am-11.30am</option>
      <option value="11.30am-1.00pm">11.30am-1.00pm</option>
    </select>
  </form>
  <br>
  <button type="button">Submit</button>  <br><br><br> <br><br><br>
  
  <div class ="f5"> 
  <h3 class="square" > <h3>
    <h4> &nbsp;&nbsp;Course is available. Contact advisor for enrollment </h4>
  </div>
    
 
   
  </div>


  <section class="footer">
    <center>
    <div class="footer-desc">
    &copy;EDUQuest 2021. Developed with <span style="color: red; font-size: 1.5rem">❤</span> by EDUQuest.
    </div>
  </center>
</section>  

    <style>
      .footer{
        background: #121212;
        color: #fff;
        
      }

      .footer .footer-desc{
        margin-top: 40px;
      }
    </style>

</body>
</html>